name:                topmovies
version:             0.1.0.0
github:              "githubuser/topmovies"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/topmovies#readme>

dependencies:
- base >= 4.7 && < 5
- direct-sqlite
- HTTP
- network
- resourcet
- conduit
- http-client
- http-client-tls
- http-conduit
- http-types
- network-uri
- conduit-extra
- text
- time
- bytestring
- HDBC
- HDBC-sqlite3
- aeson
library:
  source-dirs: src

executables:
  topmovies-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - topmovies

tests:
  topmovies-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - topmovies
